### ISSUE TITLE
Not a windows path

### ISSUE THREAD

**Issue by annazeller** [jguyomard/docker-laravel#10]
Within the php Dockerfile the composer installation is called and then later mounted to $HOME/.composer in the docker-compose.yml. This is not a windows path and therefore, the container won't start up... I'm fairly new to docker, do you have any solutions? Thanks in advance!

**Comment by jguyomard** [comment]
Hello,

I'm not a windows user, but i can see two solutions:
- remove line 8 in `docker-compose.yml`
`composer install` will be slower, but will work.
- or, replace local `$HOME/.composer/` path by `C:\Users\<your-user>\AppData\Roaming\Composer`

**Comment by annazeller** [comment]
Hey, thanks for the reply. Your first idea is exactly what I ended up doing because we're sharing a project between mac and windows users.
