### ISSUE TITLE
Upgrading to PHP 7.3

### ISSUE THREAD

**Issue by karllhughes** [jguyomard/docker-laravel#14]
I've got to upgrade my images to PHP 7.3 at work. If you're interested, I can make a PR here to add my changes? If not, I'm happy to live in my own fork for now.

Thanks!

**Comment by karllhughes** [comment]
Made a fork, the only real change was libzip:

https://github.com/thegraidenetwork/docker-laravel/commit/0929f7a72bc1e4c6fa9a1ae83cb819f77cfa81bf#diff-e60689757234d67dd9fbef41b1d89173R11

Happy to make a PR, just let me know 😄

**Comment by jguyomard** [comment]
Hello,

Yes, if you can make a PR, that would be awesome :)

**Comment by karllhughes** [comment]
PR Made. Thanks!

**Comment by jguyomard** [comment]
PR merged and docker image built :)
https://cloud.docker.com/repository/docker/jguyomard/laravel-php/tags

Thanks!
