### ISSUE TITLE
Nginx : 413 Request Entity Too Large

### ISSUE THREAD

**Issue by tonyyb** [jguyomard/docker-laravel#6]
Hi,

I've got an error (413 Request Entity Too Large) when i try to upload a file from my application (3mo).
I think you can fix it with this configuration :

 ```
server {
....
        client_max_body_size 20M;
....
    }
```

**Comment by jguyomard** [comment]
Hello,

Yes, it's a good idea!
Can you make a pull request, please?

**Comment by tonyyb** [comment]
Done :)

**Comment by jguyomard** [comment]
Merged :)
